### ISSUE TITLE
tellbot-0.5.1.1 does not compile

### ISSUE THREAD

**Issue by peti** [phaazon/tellbot#7]
See http://hydra.cryp.to/build/781949/log/raw for a complete build log.

**Comment by phaazon** [comment]
Hm, weird. Do you use the tellbot? I added a feature that might be very dangerous (it parses URLs and request their body to extract the title).

**Comment by peti** [comment]
I'm not a tellbot user. I just package the library for NixOS and run across the build error in the course of that. Would it be possible to get an updated  version on Hackage that fixes this issue?

**Comment by phaazon** [comment]
Sure, I’ll do that tonight.

**Comment by phaazon** [comment]
That should be fixed on the current HEAD. May you test before I upload on hackage? :) Thanks @peti !

**Comment by peti** [comment]
I am sorry, but it's difficult for me to test the build from a git repository. Our whole infrastructure is geared towards building Hackage. Once the new version shows up there, we'll build it automatically within 60 minutes, though.

**Comment by phaazon** [comment]
Ok, I’ll release it because it adds an important patch anyways.

**Comment by phaazon** [comment]
[Last log](http://hydra.cryp.to/build/784363/nixlog/2/raw). I think I got it. Pushing new patch soon.

**Comment by peti** [comment]
Cool, thank you!
