### ISSUE TITLE
Please add support for recent versions of errors

### ISSUE THREAD

**Issue by peti** [phaazon/tellbot#8]
After updating NixOS to errors 2.x, we can no longer built your package: http://packdeps.haskellers.com/feed?needle=tellbot.

**Comment by phaazon** [comment]
I’m on it! :)

**Comment by phaazon** [comment]
Ok, breaking changes in my code. I’ll fix that today.

**Comment by phaazon** [comment]
Fixed. I stopped using `errors`.
